[package]
name = "merkle_accel"
version = "0.1.0"
edition = "2021"

[lib]
name = "merkle_accel"
path = "src/lib.rs"

[dependencies]

[build-dependencies]
cc = "1.0"
cmake = "0.1.50"

[features]
cpu = []
gpu = []
fpga = []
stub = []