/**
* Copyright (C) 2019-2021 Xilinx, Inc
*
* Licensed under the Apache License, Version 2.0 (the "License"). You may
* not use this file except in compliance with the License. A copy of the
* License is located at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
* License for the specific language governing permissions and limitations
* under the License.
*/

///////////////////////////////////////////////////////////////////////////////
// Description: This is a wrapper of module "krnl_vadd_rtl_int"
///////////////////////////////////////////////////////////////////////////////

// default_nettype of none prevents implicit wire declaration.
`default_nettype none
`timescale 1 ns / 1 ps 
`include "env.vh"


module krnl_vadd_rtl #( 
  parameter integer  C_S_AXI_CONTROL_DATA_WIDTH = 32,
  parameter integer  C_S_AXI_CONTROL_ADDR_WIDTH = 8,
  parameter integer  C_M_AXI_GMEM_ID_WIDTH0 = 1, // log2(width)
  parameter integer  C_M_AXI_GMEM_ID_WIDTH1 = 1,
  parameter integer  C_M_AXI_GMEM_ID_WIDTH2 = 1,
  parameter integer  C_M_AXI_GMEM_ID_WIDTH3 = 1,
  parameter integer  C_M_AXI_GMEM_ID_WIDTH4 = 1,
  parameter integer  C_M_AXI_GMEM_ADDR_WIDTH = 64,
  parameter integer  C_M_AXI_GMEM_DATA_WIDTH = 512
)
(
  // System signals
  input  wire  ap_clk,
  input  wire  ap_rst_n,
//-------------------------------------------------------------
//-------------------------------------------------------------

  // AXI4 master interface 
  output wire                                 m_axi_gmem0_AWVALID,
  input  wire                                 m_axi_gmem0_AWREADY,
  output wire [C_M_AXI_GMEM_ADDR_WIDTH-1:0]   m_axi_gmem0_AWADDR,
  output wire [C_M_AXI_GMEM_ID_WIDTH0 - 1:0]  m_axi_gmem0_AWID,
  output wire [7:0]                           m_axi_gmem0_AWLEN,
  output wire [2:0]                           m_axi_gmem0_AWSIZE,
  // Tie-off AXI4 transaction options that are not being used.
  output wire [1:0]                           m_axi_gmem0_AWBURST,
  output wire [1:0]                           m_axi_gmem0_AWLOCK,
  output wire [3:0]                           m_axi_gmem0_AWCACHE,
  output wire [2:0]                           m_axi_gmem0_AWPROT,
  output wire [3:0]                           m_axi_gmem0_AWQOS,
  output wire [3:0]                           m_axi_gmem0_AWREGION,
  output wire                                 m_axi_gmem0_WVALID,
  input  wire                                 m_axi_gmem0_WREADY,
  output wire [C_M_AXI_GMEM_DATA_WIDTH-1:0]   m_axi_gmem0_WDATA,
  output wire [C_M_AXI_GMEM_DATA_WIDTH/8-1:0] m_axi_gmem0_WSTRB,
  output wire                                 m_axi_gmem0_WLAST,
  output wire                                 m_axi_gmem0_ARVALID,
  input  wire                                 m_axi_gmem0_ARREADY,
  output wire [C_M_AXI_GMEM_ADDR_WIDTH-1:0]   m_axi_gmem0_ARADDR,
  output wire [C_M_AXI_GMEM_ID_WIDTH0 -1:0]   m_axi_gmem0_ARID,
  output wire [7:0]                           m_axi_gmem0_ARLEN,
  output wire [2:0]                           m_axi_gmem0_ARSIZE,
  output wire [1:0]                           m_axi_gmem0_ARBURST,
  output wire [1:0]                           m_axi_gmem0_ARLOCK,
  output wire [3:0]                           m_axi_gmem0_ARCACHE,
  output wire [2:0]                           m_axi_gmem0_ARPROT,
  output wire [3:0]                           m_axi_gmem0_ARQOS,
  output wire [3:0]                           m_axi_gmem0_ARREGION,
  input  wire                                 m_axi_gmem0_RVALID,
  output wire                                 m_axi_gmem0_RREADY,
  input  wire [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA,
  input  wire                                 m_axi_gmem0_RLAST,
  input  wire [C_M_AXI_GMEM_ID_WIDTH0 - 1:0]  m_axi_gmem0_RID,
  input  wire [1:0]                           m_axi_gmem0_RRESP,
  input  wire                                 m_axi_gmem0_BVALID,
  output wire                                 m_axi_gmem0_BREADY,
  input  wire [1:0]                           m_axi_gmem0_BRESP,
  input  wire [C_M_AXI_GMEM_ID_WIDTH0 - 1:0]  m_axi_gmem0_BID,

//-------------------------------------------------------------
//-------------------------------------------------------------

  // AXI4 master interface 
  output wire                                 m_axi_gmem1_AWVALID,
  input  wire                                 m_axi_gmem1_AWREADY,
  output wire [C_M_AXI_GMEM_ADDR_WIDTH-1:0]   m_axi_gmem1_AWADDR,
  output wire [C_M_AXI_GMEM_ID_WIDTH1 - 1:0]  m_axi_gmem1_AWID,
  output wire [7:0]                           m_axi_gmem1_AWLEN,
  output wire [2:0]                           m_axi_gmem1_AWSIZE,
  // Tie-off AXI4 transaction options that are not being used.
  output wire [1:0]                           m_axi_gmem1_AWBURST,
  output wire [1:0]                           m_axi_gmem1_AWLOCK,
  output wire [3:0]                           m_axi_gmem1_AWCACHE,
  output wire [2:0]                           m_axi_gmem1_AWPROT,
  output wire [3:0]                           m_axi_gmem1_AWQOS,
  output wire [3:0]                           m_axi_gmem1_AWREGION,
  output wire                                 m_axi_gmem1_WVALID,
  input  wire                                 m_axi_gmem1_WREADY,
  output wire [C_M_AXI_GMEM_DATA_WIDTH-1:0]   m_axi_gmem1_WDATA,
  output wire [C_M_AXI_GMEM_DATA_WIDTH/8-1:0] m_axi_gmem1_WSTRB,
  output wire                                 m_axi_gmem1_WLAST,
  output wire                                 m_axi_gmem1_ARVALID,
  input  wire                                 m_axi_gmem1_ARREADY,
  output wire [C_M_AXI_GMEM_ADDR_WIDTH-1:0]   m_axi_gmem1_ARADDR,
  output wire [C_M_AXI_GMEM_ID_WIDTH1 -1:0]   m_axi_gmem1_ARID,
  output wire [7:0]                           m_axi_gmem1_ARLEN,
  output wire [2:0]                           m_axi_gmem1_ARSIZE,
  output wire [1:0]                           m_axi_gmem1_ARBURST,
  output wire [1:0]                           m_axi_gmem1_ARLOCK,
  output wire [3:0]                           m_axi_gmem1_ARCACHE,
  output wire [2:0]                           m_axi_gmem1_ARPROT,
  output wire [3:0]                           m_axi_gmem1_ARQOS,
  output wire [3:0]                           m_axi_gmem1_ARREGION,
  input  wire                                 m_axi_gmem1_RVALID,
  output wire                                 m_axi_gmem1_RREADY,
  input  wire [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA,
  input  wire                                 m_axi_gmem1_RLAST,
  input  wire [C_M_AXI_GMEM_ID_WIDTH1 - 1:0]  m_axi_gmem1_RID,
  input  wire [1:0]                           m_axi_gmem1_RRESP,
  input  wire                                 m_axi_gmem1_BVALID,
  output wire                                 m_axi_gmem1_BREADY,
  input  wire [1:0]                           m_axi_gmem1_BRESP,
  input  wire [C_M_AXI_GMEM_ID_WIDTH1 - 1:0]  m_axi_gmem1_BID,

//-------------------------------------------------------------
//-------------------------------------------------------------

  // AXI4 master interface 
  output wire                                 m_axi_gmem2_AWVALID,
  input  wire                                 m_axi_gmem2_AWREADY,
  output wire [C_M_AXI_GMEM_ADDR_WIDTH-1:0]   m_axi_gmem2_AWADDR,
  output wire [C_M_AXI_GMEM_ID_WIDTH2 - 1:0]  m_axi_gmem2_AWID,
  output wire [7:0]                           m_axi_gmem2_AWLEN,
  output wire [2:0]                           m_axi_gmem2_AWSIZE,
  // Tie-off AXI4 transaction options that are not being used.
  output wire [1:0]                           m_axi_gmem2_AWBURST,
  output wire [1:0]                           m_axi_gmem2_AWLOCK,
  output wire [3:0]                           m_axi_gmem2_AWCACHE,
  output wire [2:0]                           m_axi_gmem2_AWPROT,
  output wire [3:0]                           m_axi_gmem2_AWQOS,
  output wire [3:0]                           m_axi_gmem2_AWREGION,
  output wire                                 m_axi_gmem2_WVALID,
  input  wire                                 m_axi_gmem2_WREADY,
  output wire [C_M_AXI_GMEM_DATA_WIDTH-1:0]   m_axi_gmem2_WDATA,
  output wire [C_M_AXI_GMEM_DATA_WIDTH/8-1:0] m_axi_gmem2_WSTRB,
  output wire                                 m_axi_gmem2_WLAST,
  output wire                                 m_axi_gmem2_ARVALID,
  input  wire                                 m_axi_gmem2_ARREADY,
  output wire [C_M_AXI_GMEM_ADDR_WIDTH-1:0]   m_axi_gmem2_ARADDR,
  output wire [C_M_AXI_GMEM_ID_WIDTH2 -1:0]   m_axi_gmem2_ARID,
  output wire [7:0]                           m_axi_gmem2_ARLEN,
  output wire [2:0]                           m_axi_gmem2_ARSIZE,
  output wire [1:0]                           m_axi_gmem2_ARBURST,
  output wire [1:0]                           m_axi_gmem2_ARLOCK,
  output wire [3:0]                           m_axi_gmem2_ARCACHE,
  output wire [2:0]                           m_axi_gmem2_ARPROT,
  output wire [3:0]                           m_axi_gmem2_ARQOS,
  output wire [3:0]                           m_axi_gmem2_ARREGION,
  input  wire                                 m_axi_gmem2_RVALID,
  output wire                                 m_axi_gmem2_RREADY,
  input  wire [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA,
  input  wire                                 m_axi_gmem2_RLAST,
  input  wire [C_M_AXI_GMEM_ID_WIDTH2 - 1:0]  m_axi_gmem2_RID,
  input  wire [1:0]                           m_axi_gmem2_RRESP,
  input  wire                                 m_axi_gmem2_BVALID,
  output wire                                 m_axi_gmem2_BREADY,
  input  wire [1:0]                           m_axi_gmem2_BRESP,
  input  wire [C_M_AXI_GMEM_ID_WIDTH2 - 1:0]  m_axi_gmem2_BID,

//-------------------------------------------------------------
//-------------------------------------------------------------

  // AXI4 master interface 
  output wire                                 m_axi_gmem3_AWVALID,
  input  wire                                 m_axi_gmem3_AWREADY,
  output wire [C_M_AXI_GMEM_ADDR_WIDTH-1:0]   m_axi_gmem3_AWADDR,
  output wire [C_M_AXI_GMEM_ID_WIDTH3 - 1:0]  m_axi_gmem3_AWID,
  output wire [7:0]                           m_axi_gmem3_AWLEN,
  output wire [2:0]                           m_axi_gmem3_AWSIZE,
  // Tie-off AXI4 transaction options that are not being used.
  output wire [1:0]                           m_axi_gmem3_AWBURST,
  output wire [1:0]                           m_axi_gmem3_AWLOCK,
  output wire [3:0]                           m_axi_gmem3_AWCACHE,
  output wire [2:0]                           m_axi_gmem3_AWPROT,
  output wire [3:0]                           m_axi_gmem3_AWQOS,
  output wire [3:0]                           m_axi_gmem3_AWREGION,
  output wire                                 m_axi_gmem3_WVALID,
  input  wire                                 m_axi_gmem3_WREADY,
  output wire [C_M_AXI_GMEM_DATA_WIDTH-1:0]   m_axi_gmem3_WDATA,
  output wire [C_M_AXI_GMEM_DATA_WIDTH/8-1:0] m_axi_gmem3_WSTRB,
  output wire                                 m_axi_gmem3_WLAST,
  output wire                                 m_axi_gmem3_ARVALID,
  input  wire                                 m_axi_gmem3_ARREADY,
  output wire [C_M_AXI_GMEM_ADDR_WIDTH-1:0]   m_axi_gmem3_ARADDR,
  output wire [C_M_AXI_GMEM_ID_WIDTH3 -1:0]   m_axi_gmem3_ARID,
  output wire [7:0]                           m_axi_gmem3_ARLEN,
  output wire [2:0]                           m_axi_gmem3_ARSIZE,
  output wire [1:0]                           m_axi_gmem3_ARBURST,
  output wire [1:0]                           m_axi_gmem3_ARLOCK,
  output wire [3:0]                           m_axi_gmem3_ARCACHE,
  output wire [2:0]                           m_axi_gmem3_ARPROT,
  output wire [3:0]                           m_axi_gmem3_ARQOS,
  output wire [3:0]                           m_axi_gmem3_ARREGION,
  input  wire                                 m_axi_gmem3_RVALID,
  output wire                                 m_axi_gmem3_RREADY,
  input  wire [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem3_RDATA,
  input  wire                                 m_axi_gmem3_RLAST,
  input  wire [C_M_AXI_GMEM_ID_WIDTH3 - 1:0]  m_axi_gmem3_RID,
  input  wire [1:0]                           m_axi_gmem3_RRESP,
  input  wire                                 m_axi_gmem3_BVALID,
  output wire                                 m_axi_gmem3_BREADY,
  input  wire [1:0]                           m_axi_gmem3_BRESP,
  input  wire [C_M_AXI_GMEM_ID_WIDTH3 - 1:0]  m_axi_gmem3_BID,

//-------------------------------------------------------------
//-------------------------------------------------------------

  // AXI4 master interface 
  output wire                                 m_axi_gmem4_AWVALID,
  input  wire                                 m_axi_gmem4_AWREADY,
  output wire [C_M_AXI_GMEM_ADDR_WIDTH-1:0]   m_axi_gmem4_AWADDR,
  output wire [C_M_AXI_GMEM_ID_WIDTH4 - 1:0]  m_axi_gmem4_AWID,
  output wire [7:0]                           m_axi_gmem4_AWLEN,
  output wire [2:0]                           m_axi_gmem4_AWSIZE,
  // Tie-off AXI4 transaction options that are not being used.
  output wire [1:0]                           m_axi_gmem4_AWBURST,
  output wire [1:0]                           m_axi_gmem4_AWLOCK,
  output wire [3:0]                           m_axi_gmem4_AWCACHE,
  output wire [2:0]                           m_axi_gmem4_AWPROT,
  output wire [3:0]                           m_axi_gmem4_AWQOS,
  output wire [3:0]                           m_axi_gmem4_AWREGION,
  output wire                                 m_axi_gmem4_WVALID,
  input  wire                                 m_axi_gmem4_WREADY,
  output wire [C_M_AXI_GMEM_DATA_WIDTH-1:0]   m_axi_gmem4_WDATA,
  output wire [C_M_AXI_GMEM_DATA_WIDTH/8-1:0] m_axi_gmem4_WSTRB,
  output wire                                 m_axi_gmem4_WLAST,
  output wire                                 m_axi_gmem4_ARVALID,
  input  wire                                 m_axi_gmem4_ARREADY,
  output wire [C_M_AXI_GMEM_ADDR_WIDTH-1:0]   m_axi_gmem4_ARADDR,
  output wire [C_M_AXI_GMEM_ID_WIDTH4 -1:0]   m_axi_gmem4_ARID,
  output wire [7:0]                           m_axi_gmem4_ARLEN,
  output wire [2:0]                           m_axi_gmem4_ARSIZE,
  output wire [1:0]                           m_axi_gmem4_ARBURST,
  output wire [1:0]                           m_axi_gmem4_ARLOCK,
  output wire [3:0]                           m_axi_gmem4_ARCACHE,
  output wire [2:0]                           m_axi_gmem4_ARPROT,
  output wire [3:0]                           m_axi_gmem4_ARQOS,
  output wire [3:0]                           m_axi_gmem4_ARREGION,
  input  wire                                 m_axi_gmem4_RVALID,
  output wire                                 m_axi_gmem4_RREADY,
  input  wire [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem4_RDATA,
  input  wire                                 m_axi_gmem4_RLAST,
  input  wire [C_M_AXI_GMEM_ID_WIDTH4 - 1:0]  m_axi_gmem4_RID,
  input  wire [1:0]                           m_axi_gmem4_RRESP,
  input  wire                                 m_axi_gmem4_BVALID,
  output wire                                 m_axi_gmem4_BREADY,
  input  wire [1:0]                           m_axi_gmem4_BRESP,
  input  wire [C_M_AXI_GMEM_ID_WIDTH4 - 1:0]  m_axi_gmem4_BID,

//--------------- slave ---------------------------------------------------
  // AXI4-Lite slave interface
  input  wire                                    s_axi_control_AWVALID,
  output wire                                    s_axi_control_AWREADY,
  input  wire [C_S_AXI_CONTROL_ADDR_WIDTH-1:0]   s_axi_control_AWADDR,
  input  wire                                    s_axi_control_WVALID,
  output wire                                    s_axi_control_WREADY,
  input  wire [C_S_AXI_CONTROL_DATA_WIDTH-1:0]   s_axi_control_WDATA,
  input  wire [C_S_AXI_CONTROL_DATA_WIDTH/8-1:0] s_axi_control_WSTRB,
  input  wire                                    s_axi_control_ARVALID,
  output wire                                    s_axi_control_ARREADY,
  input  wire [C_S_AXI_CONTROL_ADDR_WIDTH-1:0]   s_axi_control_ARADDR,
  output wire                                    s_axi_control_RVALID,
  input  wire                                    s_axi_control_RREADY,
  output wire [C_S_AXI_CONTROL_DATA_WIDTH-1:0]   s_axi_control_RDATA,
  output wire [1:0]                              s_axi_control_RRESP,
  output wire                                    s_axi_control_BVALID,
  input  wire                                    s_axi_control_BREADY,
  output wire [1:0]                              s_axi_control_BRESP,
  output wire                                    interrupt 

);

logic gl_ap_rst_n ;

   // BUFG: General Clock Buffer
   //       Virtex UltraScale+
   // Xilinx HDL Language Template, version 2023.2

`KEEP_HIE BUFG BUFG_rst_n_inst (
      .O(gl_ap_rst_n), // 1-bit output: Clock output.
      .I(ap_rst_n)  // 1-bit input: Clock input.
   );

   // End of BUFG_inst instantiation


krnl_vadd_rtl_int #(
  .C_S_AXI_CONTROL_DATA_WIDTH  ( C_S_AXI_CONTROL_DATA_WIDTH ),
  .C_S_AXI_CONTROL_ADDR_WIDTH  ( C_S_AXI_CONTROL_ADDR_WIDTH ),
  .C_M_AXI_GMEM_ID_WIDTH0      ( C_M_AXI_GMEM_ID_WIDTH0 	),
  .C_M_AXI_GMEM_ID_WIDTH1      ( C_M_AXI_GMEM_ID_WIDTH1 	),
  .C_M_AXI_GMEM_ID_WIDTH2      ( C_M_AXI_GMEM_ID_WIDTH2 	),
  .C_M_AXI_GMEM_ID_WIDTH3      ( C_M_AXI_GMEM_ID_WIDTH3 	),
  .C_M_AXI_GMEM_ID_WIDTH4      ( C_M_AXI_GMEM_ID_WIDTH4 	),
  .C_M_AXI_GMEM_ADDR_WIDTH     ( C_M_AXI_GMEM_ADDR_WIDTH 	),
  .C_M_AXI_GMEM_DATA_WIDTH     ( C_M_AXI_GMEM_DATA_WIDTH 	)
)
inst_krnl_vadd_rtl_int (
  .ap_clk                 ( ap_clk ),
  .ap_rst_n               ( gl_ap_rst_n ),
  .m_axi_gmem0_AWVALID     ( m_axi_gmem0_AWVALID ),
  .m_axi_gmem0_AWREADY     ( m_axi_gmem0_AWREADY ),
  .m_axi_gmem0_AWADDR      ( m_axi_gmem0_AWADDR ),
  .m_axi_gmem0_AWID        ( m_axi_gmem0_AWID ),
  .m_axi_gmem0_AWLEN       ( m_axi_gmem0_AWLEN ),
  .m_axi_gmem0_AWSIZE      ( m_axi_gmem0_AWSIZE ),
  .m_axi_gmem0_AWBURST     ( m_axi_gmem0_AWBURST ),
  .m_axi_gmem0_AWLOCK      ( m_axi_gmem0_AWLOCK ),
  .m_axi_gmem0_AWCACHE     ( m_axi_gmem0_AWCACHE ),
  .m_axi_gmem0_AWPROT      ( m_axi_gmem0_AWPROT ),
  .m_axi_gmem0_AWQOS       ( m_axi_gmem0_AWQOS ),
  .m_axi_gmem0_AWREGION    ( m_axi_gmem0_AWREGION ),
  .m_axi_gmem0_WVALID      ( m_axi_gmem0_WVALID ),
  .m_axi_gmem0_WREADY      ( m_axi_gmem0_WREADY ),
  .m_axi_gmem0_WDATA       ( m_axi_gmem0_WDATA ),
  .m_axi_gmem0_WSTRB       ( m_axi_gmem0_WSTRB ),
  .m_axi_gmem0_WLAST       ( m_axi_gmem0_WLAST ),
  .m_axi_gmem0_ARVALID     ( m_axi_gmem0_ARVALID ),
  .m_axi_gmem0_ARREADY     ( m_axi_gmem0_ARREADY ),
  .m_axi_gmem0_ARADDR      ( m_axi_gmem0_ARADDR ),
  .m_axi_gmem0_ARID        ( m_axi_gmem0_ARID ),
  .m_axi_gmem0_ARLEN       ( m_axi_gmem0_ARLEN ),
  .m_axi_gmem0_ARSIZE      ( m_axi_gmem0_ARSIZE ),
  .m_axi_gmem0_ARBURST     ( m_axi_gmem0_ARBURST ),
  .m_axi_gmem0_ARLOCK      ( m_axi_gmem0_ARLOCK ),
  .m_axi_gmem0_ARCACHE     ( m_axi_gmem0_ARCACHE ),
  .m_axi_gmem0_ARPROT      ( m_axi_gmem0_ARPROT ),
  .m_axi_gmem0_ARQOS       ( m_axi_gmem0_ARQOS ),
  .m_axi_gmem0_ARREGION    ( m_axi_gmem0_ARREGION ),
  .m_axi_gmem0_RVALID      ( m_axi_gmem0_RVALID ),
  .m_axi_gmem0_RREADY      ( m_axi_gmem0_RREADY ),
  .m_axi_gmem0_RDATA       ( m_axi_gmem0_RDATA ),
  .m_axi_gmem0_RLAST       ( m_axi_gmem0_RLAST ),
  .m_axi_gmem0_RID         ( m_axi_gmem0_RID ),
  .m_axi_gmem0_RRESP       ( m_axi_gmem0_RRESP ),
  .m_axi_gmem0_BVALID      ( m_axi_gmem0_BVALID ),
  .m_axi_gmem0_BREADY      ( m_axi_gmem0_BREADY ),
  .m_axi_gmem0_BRESP       ( m_axi_gmem0_BRESP ),
  .m_axi_gmem0_BID         ( m_axi_gmem0_BID ),
  .m_axi_gmem1_AWVALID     ( m_axi_gmem1_AWVALID ),
  .m_axi_gmem1_AWREADY     ( m_axi_gmem1_AWREADY ),
  .m_axi_gmem1_AWADDR      ( m_axi_gmem1_AWADDR ),
  .m_axi_gmem1_AWID        ( m_axi_gmem1_AWID ),
  .m_axi_gmem1_AWLEN       ( m_axi_gmem1_AWLEN ),
  .m_axi_gmem1_AWSIZE      ( m_axi_gmem1_AWSIZE ),
  .m_axi_gmem1_AWBURST     ( m_axi_gmem1_AWBURST ),
  .m_axi_gmem1_AWLOCK      ( m_axi_gmem1_AWLOCK ),
  .m_axi_gmem1_AWCACHE     ( m_axi_gmem1_AWCACHE ),
  .m_axi_gmem1_AWPROT      ( m_axi_gmem1_AWPROT ),
  .m_axi_gmem1_AWQOS       ( m_axi_gmem1_AWQOS ),
  .m_axi_gmem1_AWREGION    ( m_axi_gmem1_AWREGION ),
  .m_axi_gmem1_WVALID      ( m_axi_gmem1_WVALID ),
  .m_axi_gmem1_WREADY      ( m_axi_gmem1_WREADY ),
  .m_axi_gmem1_WDATA       ( m_axi_gmem1_WDATA ),
  .m_axi_gmem1_WSTRB       ( m_axi_gmem1_WSTRB ),
  .m_axi_gmem1_WLAST       ( m_axi_gmem1_WLAST ),
  .m_axi_gmem1_ARVALID     ( m_axi_gmem1_ARVALID ),
  .m_axi_gmem1_ARREADY     ( m_axi_gmem1_ARREADY ),
  .m_axi_gmem1_ARADDR      ( m_axi_gmem1_ARADDR ),
  .m_axi_gmem1_ARID        ( m_axi_gmem1_ARID ),
  .m_axi_gmem1_ARLEN       ( m_axi_gmem1_ARLEN ),
  .m_axi_gmem1_ARSIZE      ( m_axi_gmem1_ARSIZE ),
  .m_axi_gmem1_ARBURST     ( m_axi_gmem1_ARBURST ),
  .m_axi_gmem1_ARLOCK      ( m_axi_gmem1_ARLOCK ),
  .m_axi_gmem1_ARCACHE     ( m_axi_gmem1_ARCACHE ),
  .m_axi_gmem1_ARPROT      ( m_axi_gmem1_ARPROT ),
  .m_axi_gmem1_ARQOS       ( m_axi_gmem1_ARQOS ),
  .m_axi_gmem1_ARREGION    ( m_axi_gmem1_ARREGION ),
  .m_axi_gmem1_RVALID      ( m_axi_gmem1_RVALID ),
  .m_axi_gmem1_RREADY      ( m_axi_gmem1_RREADY ),
  .m_axi_gmem1_RDATA       ( m_axi_gmem1_RDATA ),
  .m_axi_gmem1_RLAST       ( m_axi_gmem1_RLAST ),
  .m_axi_gmem1_RID         ( m_axi_gmem1_RID ),
  .m_axi_gmem1_RRESP       ( m_axi_gmem1_RRESP ),
  .m_axi_gmem1_BVALID      ( m_axi_gmem1_BVALID ),
  .m_axi_gmem1_BREADY      ( m_axi_gmem1_BREADY ),
  .m_axi_gmem1_BRESP       ( m_axi_gmem1_BRESP ),
  .m_axi_gmem1_BID         ( m_axi_gmem1_BID ),
  .m_axi_gmem2_AWVALID     ( m_axi_gmem2_AWVALID ),
  .m_axi_gmem2_AWREADY     ( m_axi_gmem2_AWREADY ),
  .m_axi_gmem2_AWADDR      ( m_axi_gmem2_AWADDR ),
  .m_axi_gmem2_AWID        ( m_axi_gmem2_AWID ),
  .m_axi_gmem2_AWLEN       ( m_axi_gmem2_AWLEN ),
  .m_axi_gmem2_AWSIZE      ( m_axi_gmem2_AWSIZE ),
  .m_axi_gmem2_AWBURST     ( m_axi_gmem2_AWBURST ),
  .m_axi_gmem2_AWLOCK      ( m_axi_gmem2_AWLOCK ),
  .m_axi_gmem2_AWCACHE     ( m_axi_gmem2_AWCACHE ),
  .m_axi_gmem2_AWPROT      ( m_axi_gmem2_AWPROT ),
  .m_axi_gmem2_AWQOS       ( m_axi_gmem2_AWQOS ),
  .m_axi_gmem2_AWREGION    ( m_axi_gmem2_AWREGION ),
  .m_axi_gmem2_WVALID      ( m_axi_gmem2_WVALID ),
  .m_axi_gmem2_WREADY      ( m_axi_gmem2_WREADY ),
  .m_axi_gmem2_WDATA       ( m_axi_gmem2_WDATA ),
  .m_axi_gmem2_WSTRB       ( m_axi_gmem2_WSTRB ),
  .m_axi_gmem2_WLAST       ( m_axi_gmem2_WLAST ),
  .m_axi_gmem2_ARVALID     ( m_axi_gmem2_ARVALID ),
  .m_axi_gmem2_ARREADY     ( m_axi_gmem2_ARREADY ),
  .m_axi_gmem2_ARADDR      ( m_axi_gmem2_ARADDR ),
  .m_axi_gmem2_ARID        ( m_axi_gmem2_ARID ),
  .m_axi_gmem2_ARLEN       ( m_axi_gmem2_ARLEN ),
  .m_axi_gmem2_ARSIZE      ( m_axi_gmem2_ARSIZE ),
  .m_axi_gmem2_ARBURST     ( m_axi_gmem2_ARBURST ),
  .m_axi_gmem2_ARLOCK      ( m_axi_gmem2_ARLOCK ),
  .m_axi_gmem2_ARCACHE     ( m_axi_gmem2_ARCACHE ),
  .m_axi_gmem2_ARPROT      ( m_axi_gmem2_ARPROT ),
  .m_axi_gmem2_ARQOS       ( m_axi_gmem2_ARQOS ),
  .m_axi_gmem2_ARREGION    ( m_axi_gmem2_ARREGION ),
  .m_axi_gmem2_RVALID      ( m_axi_gmem2_RVALID ),
  .m_axi_gmem2_RREADY      ( m_axi_gmem2_RREADY ),
  .m_axi_gmem2_RDATA       ( m_axi_gmem2_RDATA ),
  .m_axi_gmem2_RLAST       ( m_axi_gmem2_RLAST ),
  .m_axi_gmem2_RID         ( m_axi_gmem2_RID ),
  .m_axi_gmem2_RRESP       ( m_axi_gmem2_RRESP ),
  .m_axi_gmem2_BVALID      ( m_axi_gmem2_BVALID ),
  .m_axi_gmem2_BREADY      ( m_axi_gmem2_BREADY ),
  .m_axi_gmem2_BRESP       ( m_axi_gmem2_BRESP ),
  .m_axi_gmem2_BID         ( m_axi_gmem2_BID ),
  .m_axi_gmem3_AWVALID     ( m_axi_gmem3_AWVALID ),
  .m_axi_gmem3_AWREADY     ( m_axi_gmem3_AWREADY ),
  .m_axi_gmem3_AWADDR      ( m_axi_gmem3_AWADDR ),
  .m_axi_gmem3_AWID        ( m_axi_gmem3_AWID ),
  .m_axi_gmem3_AWLEN       ( m_axi_gmem3_AWLEN ),
  .m_axi_gmem3_AWSIZE      ( m_axi_gmem3_AWSIZE ),
  .m_axi_gmem3_AWBURST     ( m_axi_gmem3_AWBURST ),
  .m_axi_gmem3_AWLOCK      ( m_axi_gmem3_AWLOCK ),
  .m_axi_gmem3_AWCACHE     ( m_axi_gmem3_AWCACHE ),
  .m_axi_gmem3_AWPROT      ( m_axi_gmem3_AWPROT ),
  .m_axi_gmem3_AWQOS       ( m_axi_gmem3_AWQOS ),
  .m_axi_gmem3_AWREGION    ( m_axi_gmem3_AWREGION ),
  .m_axi_gmem3_WVALID      ( m_axi_gmem3_WVALID ),
  .m_axi_gmem3_WREADY      ( m_axi_gmem3_WREADY ),
  .m_axi_gmem3_WDATA       ( m_axi_gmem3_WDATA ),
  .m_axi_gmem3_WSTRB       ( m_axi_gmem3_WSTRB ),
  .m_axi_gmem3_WLAST       ( m_axi_gmem3_WLAST ),
  .m_axi_gmem3_ARVALID     ( m_axi_gmem3_ARVALID ),
  .m_axi_gmem3_ARREADY     ( m_axi_gmem3_ARREADY ),
  .m_axi_gmem3_ARADDR      ( m_axi_gmem3_ARADDR ),
  .m_axi_gmem3_ARID        ( m_axi_gmem3_ARID ),
  .m_axi_gmem3_ARLEN       ( m_axi_gmem3_ARLEN ),
  .m_axi_gmem3_ARSIZE      ( m_axi_gmem3_ARSIZE ),
  .m_axi_gmem3_ARBURST     ( m_axi_gmem3_ARBURST ),
  .m_axi_gmem3_ARLOCK      ( m_axi_gmem3_ARLOCK ),
  .m_axi_gmem3_ARCACHE     ( m_axi_gmem3_ARCACHE ),
  .m_axi_gmem3_ARPROT      ( m_axi_gmem3_ARPROT ),
  .m_axi_gmem3_ARQOS       ( m_axi_gmem3_ARQOS ),
  .m_axi_gmem3_ARREGION    ( m_axi_gmem3_ARREGION ),
  .m_axi_gmem3_RVALID      ( m_axi_gmem3_RVALID ),
  .m_axi_gmem3_RREADY      ( m_axi_gmem3_RREADY ),
  .m_axi_gmem3_RDATA       ( m_axi_gmem3_RDATA ),
  .m_axi_gmem3_RLAST       ( m_axi_gmem3_RLAST ),
  .m_axi_gmem3_RID         ( m_axi_gmem3_RID ),
  .m_axi_gmem3_RRESP       ( m_axi_gmem3_RRESP ),
  .m_axi_gmem3_BVALID      ( m_axi_gmem3_BVALID ),
  .m_axi_gmem3_BREADY      ( m_axi_gmem3_BREADY ),
  .m_axi_gmem3_BRESP       ( m_axi_gmem3_BRESP ),
  .m_axi_gmem3_BID         ( m_axi_gmem3_BID ),
  .m_axi_gmem4_AWVALID     ( m_axi_gmem4_AWVALID ),
  .m_axi_gmem4_AWREADY     ( m_axi_gmem4_AWREADY ),
  .m_axi_gmem4_AWADDR      ( m_axi_gmem4_AWADDR ),
  .m_axi_gmem4_AWID        ( m_axi_gmem4_AWID ),
  .m_axi_gmem4_AWLEN       ( m_axi_gmem4_AWLEN ),
  .m_axi_gmem4_AWSIZE      ( m_axi_gmem4_AWSIZE ),
  .m_axi_gmem4_AWBURST     ( m_axi_gmem4_AWBURST ),
  .m_axi_gmem4_AWLOCK      ( m_axi_gmem4_AWLOCK ),
  .m_axi_gmem4_AWCACHE     ( m_axi_gmem4_AWCACHE ),
  .m_axi_gmem4_AWPROT      ( m_axi_gmem4_AWPROT ),
  .m_axi_gmem4_AWQOS       ( m_axi_gmem4_AWQOS ),
  .m_axi_gmem4_AWREGION    ( m_axi_gmem4_AWREGION ),
  .m_axi_gmem4_WVALID      ( m_axi_gmem4_WVALID ),
  .m_axi_gmem4_WREADY      ( m_axi_gmem4_WREADY ),
  .m_axi_gmem4_WDATA       ( m_axi_gmem4_WDATA ),
  .m_axi_gmem4_WSTRB       ( m_axi_gmem4_WSTRB ),
  .m_axi_gmem4_WLAST       ( m_axi_gmem4_WLAST ),
  .m_axi_gmem4_ARVALID     ( m_axi_gmem4_ARVALID ),
  .m_axi_gmem4_ARREADY     ( m_axi_gmem4_ARREADY ),
  .m_axi_gmem4_ARADDR      ( m_axi_gmem4_ARADDR ),
  .m_axi_gmem4_ARID        ( m_axi_gmem4_ARID ),
  .m_axi_gmem4_ARLEN       ( m_axi_gmem4_ARLEN ),
  .m_axi_gmem4_ARSIZE      ( m_axi_gmem4_ARSIZE ),
  .m_axi_gmem4_ARBURST     ( m_axi_gmem4_ARBURST ),
  .m_axi_gmem4_ARLOCK      ( m_axi_gmem4_ARLOCK ),
  .m_axi_gmem4_ARCACHE     ( m_axi_gmem4_ARCACHE ),
  .m_axi_gmem4_ARPROT      ( m_axi_gmem4_ARPROT ),
  .m_axi_gmem4_ARQOS       ( m_axi_gmem4_ARQOS ),
  .m_axi_gmem4_ARREGION    ( m_axi_gmem4_ARREGION ),
  .m_axi_gmem4_RVALID      ( m_axi_gmem4_RVALID ),
  .m_axi_gmem4_RREADY      ( m_axi_gmem4_RREADY ),
  .m_axi_gmem4_RDATA       ( m_axi_gmem4_RDATA ),
  .m_axi_gmem4_RLAST       ( m_axi_gmem4_RLAST ),
  .m_axi_gmem4_RID         ( m_axi_gmem4_RID ),
  .m_axi_gmem4_RRESP       ( m_axi_gmem4_RRESP ),
  .m_axi_gmem4_BVALID      ( m_axi_gmem4_BVALID ),
  .m_axi_gmem4_BREADY      ( m_axi_gmem4_BREADY ),
  .m_axi_gmem4_BRESP       ( m_axi_gmem4_BRESP ),
  .m_axi_gmem4_BID         ( m_axi_gmem4_BID ),
  .s_axi_control_AWVALID  ( s_axi_control_AWVALID ),
  .s_axi_control_AWREADY  ( s_axi_control_AWREADY ),
  .s_axi_control_AWADDR   ( s_axi_control_AWADDR ),
  .s_axi_control_WVALID   ( s_axi_control_WVALID ),
  .s_axi_control_WREADY   ( s_axi_control_WREADY ),
  .s_axi_control_WDATA    ( s_axi_control_WDATA ),
  .s_axi_control_WSTRB    ( s_axi_control_WSTRB ),
  .s_axi_control_ARVALID  ( s_axi_control_ARVALID ),
  .s_axi_control_ARREADY  ( s_axi_control_ARREADY ),
  .s_axi_control_ARADDR   ( s_axi_control_ARADDR ),
  .s_axi_control_RVALID   ( s_axi_control_RVALID ),
  .s_axi_control_RREADY   ( s_axi_control_RREADY ),
  .s_axi_control_RDATA    ( s_axi_control_RDATA ),
  .s_axi_control_RRESP    ( s_axi_control_RRESP ),
  .s_axi_control_BVALID   ( s_axi_control_BVALID ),
  .s_axi_control_BREADY   ( s_axi_control_BREADY ),
  .s_axi_control_BRESP    ( s_axi_control_BRESP ),
  .interrupt              ( interrupt )
);
endmodule : krnl_vadd_rtl

`default_nettype wire
