#!/bin/sh
source /opt/xilinx/xrt/setup.sh
source /tools/Xilinx/Vitis/2023.2/settings64.sh
source /tools/Xilinx/Vivado/2023.2/settings64.sh
make build TARGET=hw PLATFORM=xilinx_u250_gen3x16_xdma_4_1_202210_1 |tee hw_run.log
